# Generated by Django 3.2.19 on 2023-06-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='msrp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
